'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and ,
the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

def fib(n):
    if n <= 0:
        return []
    if n == 1:
        return [1]
    result = [1, 2]
    for _ in range(n-2):
        result.append(result[-1] + result[-2])
    return result



if __name__ == '__main__':
    fib_nums = [i for i in fib(40) if i < 4_000_000]
    _sum = 0
    for n in fib_nums:
        if n % 2 == 0:
            _sum += n
    print(_sum)

